version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/yours-truly
    overwrite: true
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/yours-truly/scripts
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
    type :
      - file

hooks:

  BeforeInstall:

  AfterInstall:

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 2500
      runas: ubuntu

